version: "3"
services: 
  
  gitlab:
    image: gitlab/gitlab-ce
    ports: 
      - 8000:80
      - 443:443
  openldap:
    image: osixia/openldap:latest
    ports:
      - 636:636
      - 389:389
    environment: 
     LDAP_DOMAIN: "dexter.com.br"
     LDAP_ADMIN_PASSWORD: "4linux"

  jenkins:
    image: jenkins/jenkins
    ports: 
      - 8081:8080


